#!/usr/bin/env python3
"""Auto Cost Engine — Materials & Vendors Seed Data

20+ sample materials with real Indian brands, GST rates, vendors, and pricing.
"""

from app.models import Material, Vendor
from sqlalchemy.ext.asyncio import AsyncSession


# =============================================================================
# Vendor Master Data
# =============================================================================

VENDORS = [
    {
        "name": "Saint Gobain India Pvt Ltd",
        "vendor_code": "SG001",
        "contact_person": "Rajesh Mehta",
        "email": "sales.in@saint-gobain.com",
        "phone": "+91 22 6745 8000",
        "city": "Mumbai",
        "address": "Bandra Kurla Complex, Bandra East, Mumbai - 400051",
        "gst": "27AAACS1234A1Z5",
        "website": "www.saint-gobain.co.in",
        "payment_terms": "30 days from invoice",
        "delivery_time_days": 7,
        "moq": 10,
        "rating": 4.5,
        "categories_served": ["glass", "gypsum", "insulation"],
        "is_approved": True,
        "credit_limit": 5000000,
        "notes": "Preferred partner for glass and gypsum products",
    },
    {
        "name": "Interface India Pvt Ltd",
        "vendor_code": "IF001",
        "contact_person": "Priya Sharma",
        "email": "info.in@interface.com",
        "phone": "+91 80 4512 6000",
        "city": "Bengaluru",
        "address": "Whitefield Main Road, Bengaluru - 560066",
        "gst": "29AAACI5678B1Z6",
        "website": "www.interface.com/in",
        "payment_terms": "45 days",
        "delivery_time_days": 14,
        "moq": 50,
        "rating": 4.3,
        "categories_served": ["flooring", "carpet"],
        "is_approved": True,
        "credit_limit": 3000000,
        "notes": "Premium commercial carpet tiles supplier",
    },
    {
        "name": "Milliken India Ltd",
        "vendor_code": "MI001",
        "contact_person": "Arun Nair",
        "email": "info@millikenindia.com",
        "phone": "+91 44 4902 3000",
        "city": "Chennai",
        "address": "OMR Road, Sholinganallur, Chennai - 600119",
        "gst": "33AABCM9012L1Z9",
        "website": "www.milliken.com",
        "payment_terms": "30 days",
        "delivery_time_days": 21,
        "moq": 25,
        "rating": 4.6,
        "categories_served": ["flooring", "carpet"],
        "is_approved": True,
        "credit_limit": 2500000,
        "notes": "High-end modular carpet tiles",
    },
    {
        "name": "Godrej Interio",
        "vendor_code": "GI001",
        "contact_person": "Vikram Patel",
        "email": "interio@godrej.com",
        "phone": "+91 22 6244 1000",
        "city": "Mumbai",
        "address": "Godrej & Boyce, Pirojshanagar, Vikhroli East, Mumbai - 400079",
        "gst": "27AAACG3456H1Z8",
        "website": "www.godrejinterio.com",
        "payment_terms": "15 days",
        "delivery_time_days": 10,
        "moq": 5,
        "rating": 4.4,
        "categories_served": ["furniture", "workstation", "seating", "storage"],
        "is_approved": True,
        "credit_limit": 8000000,
        "notes": "Premium office furniture and workstations",
    },
    {
        "name": "Featherlite Offices Systems Pvt Ltd",
        "vendor_code": "FL001",
        "contact_person": "Suresh Kumar",
        "email": "sales@featherlite.in",
        "phone": "+91 80 4930 0000",
        "city": "Bengaluru",
        "address": "Hosur Road, Electronic City, Bengaluru - 560100",
        "gst": "29AAACF7890K1Z4",
        "website": "www.featherlite.in",
        "payment_terms": "30 days",
        "delivery_time_days": 14,
        "moq": 10,
        "rating": 4.2,
        "categories_served": ["furniture", "workstation", "seating"],
        "is_approved": True,
        "credit_limit": 5000000,
        "notes": "Modular workstations and office furniture",
    },
    {
        "name": "Kajaria Ceramics Ltd",
        "vendor_code": "KJ001",
        "contact_person": "Amit Jain",
        "email": "info@kajariaceramics.com",
        "phone": "+91 11 4720 2000",
        "city": "New Delhi",
        "address": "Jhandewalan Extension, New Delhi - 110055",
        "gst": "07AAACK1234L1Z1",
        "website": "www.kajariaceramics.com",
        "payment_terms": "30 days",
        "delivery_time_days": 5,
        "moq": 100,
        "rating": 4.1,
        "categories_served": ["tiling", "vitrified", "ceramic"],
        "is_approved": True,
        "credit_limit": 4000000,
        "notes": "Leading tile manufacturer in India",
    },
    {
        "name": "Asian Paints Ltd",
        "vendor_code": "AP001",
        "contact_person": "Rohan Deshmukh",
        "email": "corporate@asianpaints.com",
        "phone": "+91 22 3981 8000",
        "city": "Mumbai",
        "address": "6A, Shantinagar, Santacruz East, Mumbai - 400055",
        "gst": "27AAACA5678E1Z3",
        "website": "www.asianpaints.com",
        "payment_terms": "15 days",
        "delivery_time_days": 3,
        "moq": 5,
        "rating": 4.0,
        "categories_served": ["paint", "primer", "putty", "waterproofing"],
        "is_approved": True,
        "credit_limit": 10000000,
        "notes": "Largest paint company in India, preferred brand",
    },
    {
        "name": "Legrand India Pvt Ltd",
        "vendor_code": "LG001",
        "contact_person": "Karan Singh",
        "email": "info.in@legrand.com",
        "phone": "+91 20 2768 4000",
        "city": "Pune",
        "address": "MIDC Industrial Area, Bhosari, Pune - 411026",
        "gst": "27AABCL9012N1Z5",
        "website": "www.legrand.in",
        "payment_terms": "30 days",
        "delivery_time_days": 7,
        "moq": 20,
        "rating": 4.3,
        "categories_served": ["electrical", "switches", "cabling"],
        "is_approved": True,
        "credit_limit": 3000000,
        "notes": "Premium modular switches and electrical solutions",
    },
    {
        "name": "Greenlam Industries Ltd",
        "vendor_code": "GL001",
        "contact_person": "Deepak Agarwal",
        "email": "info@greenlam.com",
        "phone": "+91 124 467 2000",
        "city": "Gurugram",
        "address": "DLF Phase 3, Gurugram - 122002",
        "gst": "06AABCG3456P1Z2",
        "website": "www.greenlam.com",
        "payment_terms": "30 days",
        "delivery_time_days": 10,
        "moq": 30,
        "rating": 4.0,
        "categories_served": ["flooring", "laminate", "veneer"],
        "is_approved": True,
        "credit_limit": 2000000,
        "notes": "Leading laminate flooring manufacturer",
    },
    {
        "name": "Tarkett India Pvt Ltd",
        "vendor_code": "TK001",
        "contact_person": "Neha Gupta",
        "email": "info@tarkett.in",
        "phone": "+91 22 6135 6200",
        "city": "Mumbai",
        "address": "Andheri Kurla Road, Andheri East, Mumbai - 400059",
        "gst": "27AABCT7890J1Z7",
        "website": "www.tarkett.in",
        "payment_terms": "45 days",
        "delivery_time_days": 21,
        "moq": 100,
        "rating": 4.2,
        "categories_served": ["flooring", "vinyl", "linoleum"],
        "is_approved": True,
        "credit_limit": 4000000,
        "notes": "International vinyl and linoleum flooring specialist",
    },
]


# =============================================================================
# Material Master Data
# =============================================================================

MATERIALS = [
    # ---- GLASS ----
    {
        "name": "Toughened Glass 12mm Clear",
        "brand": "Saint Gobain",
        "category": "glass",
        "subcategory": "toughened_glass",
        "sku": "SG-TG-12-CLR",
        "rate": 850.0,
        "unit": "sqm",
        "gst_rate": 18,
        "hsn_code": "70071900",
        "vendor_id_ref": "SG001",
        "description": "12mm clear toughened glass for partitions and doors. Heat soaked, EN 12150 certified.",
        "min_order_qty": 5,
        "lead_time_days": 7,
        "warranty": "5 years",
        "fire_rating": "Class A",
        "is_active": True,
        "tags": ["glass", "toughened", "partition", "door"],
    },
    {
        "name": "Laminated Glass 12mm Clear",
        "brand": "Saint Gobain",
        "category": "glass",
        "subcategory": "laminated_glass",
        "sku": "SG-LM-12-CLR",
        "rate": 1200.0,
        "unit": "sqm",
        "gst_rate": 18,
        "hsn_code": "70072900",
        "vendor_id_ref": "SG001",
        "description": "12mm laminated safety glass with PVB interlayer",
        "min_order_qty": 5,
        "lead_time_days": 10,
        "warranty": "5 years",
        "fire_rating": "Class A",
        "is_active": True,
        "tags": ["glass", "laminated", "safety"],
    },
    {
        "name": "Mirror Glass 6mm Silver",
        "brand": "Modiguard",
        "category": "glass",
        "subcategory": "mirror_glass",
        "sku": "MG-MR-6-SLV",
        "rate": 650.0,
        "unit": "sqm",
        "gst_rate": 18,
        "hsn_code": "70099100",
        "vendor_id_ref": "SG001",
        "description": "6mm silver back mirror glass with anti-corrosion backing",
        "min_order_qty": 10,
        "lead_time_days": 5,
        "warranty": "3 years",
        "is_active": True,
        "tags": ["glass", "mirror"],
    },
    # ---- GYPSUM ----
    {
        "name": "Gypsum Board 12mm",
        "brand": "Saint Gobain Gyproc",
        "category": "gypsum",
        "subcategory": "gypsum_board",
        "sku": "GYB-12-STD",
        "rate": 280.0,
        "unit": "sqm",
        "gst_rate": 18,
        "hsn_code": "68091100",
        "vendor_id_ref": "SG001",
        "description": "Standard 12mm gypsum board for walls and ceilings, 1200x2400mm",
        "min_order_qty": 50,
        "lead_time_days": 5,
        "fire_rating": "Class 1",
        "is_active": True,
        "tags": ["gypsum", "partition", "ceiling"],
    },
    {
        "name": "Metal Stud 75mm",
        "brand": "Saint Gobain Gyproc",
        "category": "metal",
        "subcategory": "galvanized",
        "sku": "GYM-MT-STD75",
        "rate": 185.0,
        "unit": "nos",
        "gst_rate": 18,
        "hsn_code": "73089090",
        "vendor_id_ref": "SG001",
        "description": "Galvanized metal stud 75mm x 3000mm for partition framing",
        "min_order_qty": 50,
        "lead_time_days": 5,
        "is_active": True,
        "tags": ["metal", "stud", "partition"],
    },
    {
        "name": "Channel 75mm",
        "brand": "Saint Gobain Gyproc",
        "category": "metal",
        "subcategory": "galvanized",
        "sku": "GYM-CH-75",
        "rate": 165.0,
        "unit": "nos",
        "gst_rate": 18,
        "hsn_code": "73089090",
        "vendor_id_ref": "SG001",
        "description": "Galvanized channel 75mm x 3000mm top/bottom track",
        "min_order_qty": 50,
        "lead_time_days": 5,
        "is_active": True,
        "tags": ["metal", "channel", "partition"],
    },
    # ---- TILES ----
    {
        "name": "Vitrified Tile 600x600mm",
        "brand": "Kajaria",
        "category": "tiling",
        "subcategory": "vitrified_tile",
        "sku": "KJ-VT-6060",
        "rate": 75.0,
        "unit": "sqm",
        "gst_rate": 18,
        "hsn_code": "69089090",
        "vendor_id_ref": "KJ001",
        "description": "Double charge vitrified tiles 600x600mm, polished finish",
        "min_order_qty": 100,
        "lead_time_days": 5,
        "warranty": "10 years",
        "is_active": True,
        "tags": ["tile", "vitrified", "flooring"],
    },
    {
        "name": "Ceramic Wall Tile 300x600mm",
        "brand": "Kajaria",
        "category": "tiling",
        "subcategory": "ceramic_tile",
        "sku": "KJ-CT-3060",
        "rate": 55.0,
        "unit": "sqm",
        "gst_rate": 18,
        "hsn_code": "69089090",
        "vendor_id_ref": "KJ001",
        "description": "Glazed ceramic wall tiles 300x600mm for toilet backsplash",
        "min_order_qty": 100,
        "lead_time_days": 5,
        "warranty": "5 years",
        "is_active": True,
        "tags": ["tile", "ceramic", "wall"],
    },
    # ---- FLOORING ----
    {
        "name": "Commercial Carpet Tiles 500x500mm",
        "brand": "Interface",
        "category": "flooring",
        "subcategory": "carpet_tile",
        "sku": "IF-CT-5050",
        "rate": 950.0,
        "unit": "sqm",
        "gst_rate": 18,
        "hsn_code": "57050039",
        "vendor_id_ref": "IF001",
        "description": "Modular carpet tiles 500x500mm, loop pile, 15 colors available",
        "min_order_qty": 50,
        "lead_time_days": 14,
        "warranty": "10 years",
        "fire_rating": "Class 1",
        "is_active": True,
        "tags": ["carpet", "tile", "flooring", "commercial"],
    },
    {
        "name": "Broadloom Carpet 4m Wide",
        "brand": "Milliken",
        "category": "flooring",
        "subcategory": "carpet",
        "sku": "MI-BL-4M",
        "rate": 1200.0,
        "unit": "sqm",
        "gst_rate": 18,
        "hsn_code": "57050039",
        "vendor_id_ref": "MI001",
        "description": "Broadloom carpet 4m width, tufted loop pile, heavy commercial grade",
        "min_order_qty": 25,
        "lead_time_days": 21,
        "warranty": "10 years",
        "fire_rating": "Class 1",
        "is_active": True,
        "tags": ["carpet", "broadloom", "flooring"],
    },
    {
        "name": "Laminate Flooring 8mm",
        "brand": "Greenlam",
        "category": "flooring",
        "subcategory": "laminate",
        "sku": "GL-LM-8MM",
        "rate": 450.0,
        "unit": "sqm",
        "gst_rate": 18,
        "hsn_code": "44111400",
        "vendor_id_ref": "GL001",
        "description": "8mm AC4 laminate flooring with attached underlayment",
        "min_order_qty": 30,
        "lead_time_days": 10,
        "warranty": "15 years",
        "fire_rating": "Class Cfl-s1",
        "is_active": True,
        "tags": ["laminate", "flooring", "wooden"],
    },
    {
        "name": "Vinyl Sheet Flooring 2mm",
        "brand": "Tarkett",
        "category": "flooring",
        "subcategory": "vinyl_sheet",
        "sku": "TK-VS-2MM",
        "rate": 680.0,
        "unit": "sqm",
        "gst_rate": 18,
        "hsn_code": "39181090",
        "vendor_id_ref": "TK001",
        "description": "Heterogeneous vinyl sheet 2mm, homogeneous wear layer 0.55mm",
        "min_order_qty": 100,
        "lead_time_days": 21,
        "warranty": "10 years",
        "fire_rating": "Class Bfl-s1",
        "is_active": True,
        "tags": ["vinyl", "flooring", "sheet"],
    },
    # ---- PAINT ----
    {
        "name": "Interior Emulsion Paint",
        "brand": "Asian Paints",
        "category": "paint",
        "subcategory": "interior_emulsion",
        "sku": "AP-IE-20L",
        "rate": 4800.0,
        "unit": "nos",
        "gst_rate": 18,
        "hsn_code": "32091000",
        "vendor_id_ref": "AP001",
        "description": "Royale Shyne Luxury Emulsion, 20L bucket, for interior walls",
        "min_order_qty": 1,
        "lead_time_days": 3,
        "warranty": "7 years",
        "is_active": True,
        "tags": ["paint", "emulsion", "interior"],
    },
    {
        "name": "Water Based Primer",
        "brand": "Asian Paints",
        "category": "paint",
        "subcategory": "primer",
        "sku": "AP-PR-20L",
        "rate": 2800.0,
        "unit": "nos",
        "gst_rate": 18,
        "hsn_code": "32091000",
        "vendor_id_ref": "AP001",
        "description": "Water-based primer undercoat, 20L bucket",
        "min_order_qty": 1,
        "lead_time_days": 3,
        "is_active": True,
        "tags": ["primer", "paint"],
    },
    {
        "name": "Wall Care Putty 20kg",
        "brand": "Asian Paints",
        "category": "paint",
        "subcategory": "putty",
        "sku": "AP-WP-20KG",
        "rate": 650.0,
        "unit": "bag",
        "gst_rate": 18,
        "hsn_code": "32149090",
        "vendor_id_ref": "AP001",
        "description": "Waterproof wall putty, white cement based, 20kg bag",
        "min_order_qty": 5,
        "lead_time_days": 3,
        "is_active": True,
        "tags": ["putty", "wall", "finish"],
    },
    # ---- ELECTRICAL ----
    {
        "name": "Modular Switch Plate 6 Module",
        "brand": "Legrand",
        "category": "electrical",
        "subcategory": "switches",
        "sku": "LG-SW-6M",
        "rate": 350.0,
        "unit": "nos",
        "gst_rate": 18,
        "hsn_code": "85369090",
        "vendor_id_ref": "LG001",
        "description": "6-module switch plate with plain cover, Mystic White series",
        "min_order_qty": 10,
        "lead_time_days": 5,
        "warranty": "2 years",
        "is_active": True,
        "tags": ["switch", "electrical", "modular"],
    },
    {
        "name": "PVC Conduit Pipe 20mm 3m",
        "brand": "Legrand",
        "category": "electrical",
        "subcategory": "pvc_conduit",
        "sku": "LG-PC-20-3M",
        "rate": 75.0,
        "unit": "nos",
        "gst_rate": 18,
        "hsn_code": "85469010",
        "vendor_id_ref": "LG001",
        "description": "PVC conduit pipe 20mm OD, 3m length, ISI marked",
        "min_order_qty": 50,
        "lead_time_days": 5,
        "is_active": True,
        "tags": ["conduit", "electrical", "pvc"],
    },
    {
        "name": "Copper Wire 1.5 sqmm (90m)",
        "brand": "Legrand",
        "category": "electrical",
        "subcategory": "copper_wire",
        "sku": "LG-CW-1.5-90M",
        "rate": 2450.0,
        "unit": "roll",
        "gst_rate": 18,
        "hsn_code": "85441110",
        "vendor_id_ref": "LG001",
        "description": "1.5 sqmm single core copper wire, FR PVC insulation, 90m coil",
        "min_order_qty": 1,
        "lead_time_days": 5,
        "is_active": True,
        "tags": ["wire", "copper", "electrical"],
    },
    # ---- FURNITURE ----
    {
        "name": "Workstation 1500x1500mm with Panel",
        "brand": "Godrej Interio",
        "category": "furniture",
        "subcategory": "workstation",
        "sku": "GI-WS-1515",
        "rate": 28500.0,
        "unit": "nos",
        "gst_rate": 18,
        "hsn_code": "94033090",
        "vendor_id_ref": "GI001",
        "description": "Modular workstation 1500x1500mm with 1200mm panel, cable management",
        "min_order_qty": 5,
        "lead_time_days": 10,
        "warranty": "5 years",
        "is_active": True,
        "tags": ["workstation", "furniture", "office"],
    },
    {
        "name": "Ergonomic Chair Mid-Back",
        "brand": "Featherlite",
        "category": "furniture",
        "subcategory": "seating",
        "sku": "FL-EC-MB",
        "rate": 12500.0,
        "unit": "nos",
        "gst_rate": 18,
        "hsn_code": "94017100",
        "vendor_id_ref": "FL001",
        "description": "Mid-back ergonomic chair with lumbar support, 3D armrests, gas lift",
        "min_order_qty": 5,
        "lead_time_days": 14,
        "warranty": "3 years",
        "is_active": True,
        "tags": ["chair", "ergonomic", "office"],
    },
    {
        "name": "Flush Door 35mm 900x2100mm",
        "brand": "Godrej Interio",
        "category": "wood",
        "subcategory": "flush_door",
        "sku": "GI-FD-35-9021",
        "rate": 4500.0,
        "unit": "nos",
        "gst_rate": 18,
        "hsn_code": "44182010",
        "vendor_id_ref": "GI001",
        "description": "35mm solid core flush door, 900x2100mm, pre-finished",
        "min_order_qty": 2,
        "lead_time_days": 7,
        "warranty": "5 years",
        "is_active": True,
        "tags": ["door", "flush", "wood"],
    },
]


# =============================================================================
# Seed function
# =============================================================================

async def seed_materials_and_vendors(session: AsyncSession) -> int:
    """Seed materials and vendors. Returns count of materials created."""
    from sqlalchemy import select

    # Insert vendors
    vendor_map = {}  # code -> id
    for v in VENDORS:
        existing = await session.execute(
            select(Vendor).where(Vendor.vendor_code == v["vendor_code"])
        )
        if not existing.scalar_one_or_none():
            vendor = Vendor(**v)
            session.add(vendor)
            await session.flush()
            vendor_map[v["vendor_code"]] = vendor.id
        else:
            vend = existing.scalar_one()
            vendor_map[v["vendor_code"]] = vend.id

    print(f"  ✓ {len(VENDORS)} vendors loaded/verified")

    # Insert materials
    count = 0
    for m in MATERIALS:
        existing = await session.execute(
            select(Material).where(Material.sku == m["sku"])
        )
        if existing.scalar_one_or_none():
            continue

        vendor_code = m.pop("vendor_id_ref", None)
        vendor_id = vendor_map.get(vendor_code) if vendor_code else None

        material = Material(
            **m,
            vendor_id=vendor_id,
        )
        session.add(material)
        count += 1

    await session.commit()
    print(f"  ✓ {count} materials loaded (from {len(MATERIALS)} defined)")
    return count
